markdown: rdiscount
permalink: /:title.html
destination: ../../public/blog
auto: true
exclude:
  - Rakefile
  - Gemfile
  - .gitignore
author: Custom Helix Ltda
gravatar: 9c7d80ebc20ab8994e51b9f7518909ae
email: blog@customhelix.com
web: http://customhelix.github.com
twitter: CustomHelix
github: CustomHelix
